spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: core
              uri: http://localhost:8081
              predicates:
                - Path=/api/core/**
