spring:
  application:
    name: polyshelf
  datasource:
    url: jdbc:postgresql://localhost:5432/polyshelf_db
    username: polyshelf_user
    password: polyshelf_password
  flyway:
    enabled: true
    locations: classpath:db/migration